### ISSUE TITLE
mongo_dart doesn't work with flutter web

### ISSUE THREAD

**Issue by austinmarner** [mongo-dart/mongo_dart#166] opened 2019-10-21 15:39 UTC
I wanted to port my App to the web so I used flutter web from flutter dev channel but seems like that the App doesn't work with mongo_dart on the web, without mongo_dart it works perfectly, then later I. understood that socket objects cant be used in web

Console Logs from chromium:

errors.dart:145 Uncaught (in promise) Error: Unsupported operation: Socket constructor
at Object.throw_ [as throw] (errors.dart:194)
at Function._connect (io_patch.dart:477)
at Function.connect (socket.dart:740)
at mongo_dart._Connection.new.connect (connection.dart:76)
at mongo_dart._ConnectionManager.new._connect (connection_manager.dart:23)
at _connect.next ()
at runBody (async_patch.dart:84)
at Object._async [as async] (async_patch.dart:123)
at mongo_dart._ConnectionManager.new.[_connect] (connection_manager.dart:22)
at connection_manager.dart:58
at future.dart:492
at future.dart:534
at _RootZone.runUnaryGuarded (zone.dart:1314)
at zone.dart:1353
at Function.doWhile (future.dart:549)
at Function.forEach (future.dart:490)
at mongo_dart._ConnectionManager.new.open (connection_manager.dart:59)
at db.dart:220
at Function.sync (future.dart:224)
at mongo_dart.Db.new.open (db.dart:207)
at main$ (main.dart:40)
at main$.next ()
at runBody (async_patch.dart:84)
at Object._async [as async] (async_patch.dart:123)
at Object.main$ [as main] (main.dart:39)
at main$ (main_web_entrypoint.dart:9)
at main$.next ()
at onValue (async_patch.dart:45)
at _RootZone.runUnary (zone.dart:1379)
at _FutureListener.thenAwait.handleValue (future_impl.dart:137)
at handleValueCallback (future_impl.dart:678)
at Function._propagateToListeners (future_impl.dart:707)
at async._AsyncCallbackEntry.new.callback (future_impl.dart:387)
at Object._microtaskLoop (schedule_microtask.dart:41)
at _startMicrotaskLoop (schedule_microtask.dart:50)
at async_patch.dart:166

**Comment by thosakwe** [comment] 2019-10-21 15:45
Yeah, this package will never work on the Web, since you can only open a TCP socket where `dart:io` is available. Typically, though, your app won't directly connect to the database, but instead you'll likely have an API in the middle.

Going to close this, though, as it's not a bug.

**Closed by thosakwe** 2019-10-21 15:45 UTC

**Comment by jgfoster** [comment] 2021-06-20 04:09
I'd appreciate more of an explanation of the architectural issues. If Dart allows us to create an Android app, an iOS app, and a Web app, and connecting to MongoDB from Android and iOS is fine, why would one add an extra layer just because you deployed to a web app?

**Comment by giorgiofran** [comment] 2021-06-20 07:11
At present Dart has two different packages for web and "native" applications: `dart:html` and `dart:io`.  They are not compatible, in the sense that if you use one in an application you cannot use the other.
This is because, for example, the `File` class behave differently in a web app and in a native one.

In detail, the `dart:html` package does not allow socket connections (not directly). As mongo_dart depends on sockets, it cannot run when you use `dart:html`.

Recently I have seen a package that claims to be able to emulate the `dart:io` functionalities also in a web environment.
If it work, maybe we'll be able to overcome this limitation.

**Comment by jgfoster** [comment] 2021-06-20 13:38
Thanks, that helps a lot. From the earlier comment I thought that it wouldn't be a good idea to go directly to MongoDB. Now I understand that the it is an implementation limitation instead, which makes more sense. Again, thanks!
