### ISSUE TITLE
Implement insertOne

### ISSUE THREAD

**Issue by tejainece** [mongo-dart/mongo_dart#138] opened 2018-09-19 08:05 UTC
Implement [insertOne](https://docs.mongodb.com/manual/reference/method/db.collection.insertOne/), so one can get the inserted id.

**Comment by vadimtsushko** [comment] 2018-09-19 08:55
I think it is a duplicate of https://github.com/mongo-dart/mongo_dart/issues/62
Isn't it?

**Comment by tejainece** [comment] 2018-09-19 09:01
Kinda like solution for it. Yes. Should we move this there?

**Comment by vadimtsushko** [comment] 2018-09-19 09:04
Does not it help?
https://stackoverflow.com/questions/14186321/dart-mongodb-get-id-after-insert

**Comment by tejainece** [comment] 2018-09-19 09:08
That is what I do now. Mongo's `insertOne` returns the auto insert id.

**Comment by giorgiofran** [comment] 2021-04-01 16:38
insertOne has been implemented in last published pre-release (null-safety compliant).

**Comment by giorgiofran** [comment] 2021-04-15 17:30
I close this issue, feel free to open a new one if needed.

**Closed by giorgiofran** 2021-04-15 17:30 UTC
