### ISSUE TITLE
Add watch function to listen the collection changes.

### ISSUE THREAD

**Issue by developershafeek** [mongo-dart/mongo_dart#208] opened 2020-12-31 09:04 UTC

**Comment by giorgiofran** [comment] 2020-12-31 19:39
Duplicate of #192

**Comment by giorgiofran** [comment] 2021-01-13 17:15
A new development release have been published. It contains many improvements, among others, watch(), bulkWrite() (partial...) and Decimal 128. If you can, please, give it a try and report bugs and suggestions.

**Comment by giorgiofran** [comment] 2021-03-29 12:25
Final release has landed. I close this issue.

**Closed by giorgiofran** 2021-03-29 12:25 UTC
