### ISSUE TITLE
Does it support flutter web?

### ISSUE THREAD

**Issue by TomerconDevelopers** [mongo-dart/mongo_dart#187] opened 2020-06-07 19:49 UTC
I used this in Android successfully.Now I require this useful package in web.

**Comment by rknell** [comment] 2020-06-16 01:29
It should, because its pure dart. However im not the dev. Give it a go.

**Comment by TomerconDevelopers** [comment] 2020-06-21 06:23
Its not working

**Comment by tomrozb** [comment] 2020-07-10 18:41
It won't work as dart:io is not available for flutter web. This is a duplicate BTW

**Comment by Ahmadre** [comment] 2020-07-31 22:48
> It won't work as dart:io is not available for flutter web. This is a duplicate BTW

Time for a platform_interface I think 😄

**Comment by giorgiofran** [comment] 2020-08-25 07:14
as @tomrozb already told, the problem is the compatibility with dart:io. If the package uses dart:io, OK, otherwise if it uses dart:html, mongo_dart will not work. The reason is that mongo_dart needs to use sockets that are not present in dart:html.
Unfortunately dart:io and dart:html are not compatible, or you use one or the other.
Flutter/android and Flutter/IOS use dart:io, so no problem, while flutter/web uses dart:html, and this is what is causing your problem.
More in general, VM programs like servers or command line apps works fine (dart:io) while normal web apps or angular-dart apps cannot use this package (because of dart:html).
I close this issue, feel free to reopen it if you have more questions.

**Closed by giorgiofran** 2020-08-25 07:14 UTC

**Comment by mmcc007** [comment] 2020-08-28 08:05
AFAIK dart:html has support for [web sockets](https://en.wikipedia.org/wiki/WebSocket), and it is possible to import dart:html/dart:io [conditionally](https://dart.dev/guides/libraries/create-library-packages#conditionally-importing-and-exporting-library-files). Would be awesome to have this driver work on the web as well as iOS/Android/Server.

**Comment by giorgiofran** [comment] 2020-08-28 14:37
I'm not an expert, but, AFAIK, websockets only transfer data on http and https protocols. You cannot connect to a raw socket like the mongod one. You need a websocket server.
But, as I told you, maybe a solution exists, and if you can give me some documentation about it, I will study it.
By the way, I tried to make a small test project, but the dart implementation of http web sockets only accepts schemes "ws" and "wss". Trying to connect to mongod with "ws" scheme instead of "mongodb" is rejected by the server.

**Comment by mmcc007** [comment] 2020-08-28 16:55
I don't think there is anyway around the websocket server requirement to convert a websocket to a socket. Even gRPCWeb [requires](https://grpc.io/docs/languages/web/basics/) it. As mentioned in the gRPCWeb example, a common approach is to use [Envoy](https://www.envoyproxy.io/) as a proxy between websocket and socket. My guess is most API's in the cloud that support websockets use envoy.   

MongoDBs Stitch service allows connection to a Mongo DB directly from the web. My guess is they are using Envoy. 
They require using an auth step from an auth provider from companies such as google/AWS or others.

So it looks like running the driver on the web would require an Envoy proxy and an auth step of some kind. The simplest auth step is probably to just add the user to the mongodb server via a web server. Of course, depending on the use case, the auth step can be skipped, so just the Envoy proxy would be required.

A nice convenience with this approach is that Envoy apparently has configurable support for MongoDB connections. So no coding should be required on the Envoy side.

Just my 2 cents.

**Comment by giorgiofran** [comment] 2020-08-28 18:07
This could be a solution. The problem is to know how many people could be interested in having to set up a proxy in order to connect from the web.
