### ISSUE TITLE
Are there plans to support watch()?

### ISSUE THREAD

**Issue by mmcc007** [mongo-dart/mongo_dart#192] opened 2020-08-28 08:12 UTC
MongoDB has support for subscribing to a stream to [listen for changes to a collection](https://www.mongodb.com/blog/post/an-introduction-to-change-streams). Their supported drivers implement this feature. Are there any plans to implement this `watch()` feature for this driver?

**Comment by giorgiofran** [comment] 2020-08-28 08:30
It's a nice feature, but we have not yet considered to insert it in the package. You know, the problem is always time constraints.

**Comment by mmcc007** [comment] 2020-08-28 17:18
Time waits for no man unfortunately! :(

The options available to us poor devs who want to use the watch() feature is to either:

1. Run the server in a language that has a driver that supports watch().
For example java.
1. Create a mini proxy server to use a driver that has watch(). 
For example, using gRPC to a server that is running the Java driver. 
1. Add watch() in a PR

Since I already have a server in dart that uses gRPC, I am tending towards the second option.

How difficult is it to add the watch() to the driver?

**Comment by giorgiofran** [comment] 2020-08-29 06:56
It is complex.

**Comment by aytunch** [comment] 2020-09-04 21:13
@mmcc007 I just found out about gRPC and Dart and liked the idea a lot so started saerching for a DB solution which goes well with these two. I want to ditch Firebase because of many limitations. Are you glad with gRPC using dart in terms of performance. What will you do concerning watch functionality? It is really a very important feature. Lastly where do you host these? On google cloud? Please share your experience:D

**Comment by mmcc007** [comment] 2020-09-05 03:05
I agree it is important to avoid vendor lock-in and sometimes limited functionality (Cloud Firestore is optimized for performance and leaves out some features as a result). For me, I was interested in MongoDB's geospatial features (as well as the watch() capability). 

Using a few tutorials, last weekend, I put together a mini-project using gRPC calls from Flutter to make geospatial queries on MongoDB. 

The server is written in Java and connects to MongoDB using MongoDB's Java driver. Flutter makes calls to the Java server via gRPC. It does not use `watch()` as it was not required. 

If you want to limit your exposure to a language other then Dart on the server-side, it is possible to create a Dart server to talk to the Java server and do other things you may need for your application. Support for Dart on the server-side seems limited, so I avoided that for now.

The Flutter app draws a neighborhood on the map using a polygon received from MongoDB. The app allows a user to select a point on the map. A call is made to the Java server, which runs a geospatial query on MongoDB and returns a result. The user then gets a message indicating whether the point is in the neighborhood or not.

![image](https://user-images.githubusercontent.com/1980785/92296067-7b31bc80-eee5-11ea-8aec-7f8dfa093403.png)

Making this production-ready would require adding security and deploying in a scalable environment (see https://github.com/yidongnan/grpc-spring-boot-starter). Not for the faint of heart.

Source code for my weekend project:
https://github.com/mmcc007/grpc_series_flutter
Links to the relevant tutorials are referenced in the source code where used.

There is limited support for Dart/Flutter on MongoDB, but eventually it will get better.

The performance seems good. Not sure how it will scale. I used a free database in cloud from MongoDB. The Java server was running on my local computer. 

I haven't settled on a deployment strategy, for the Java server. But there are several options that should scale.

For the moment, in my real project, I am using Cloud Firebase for the `watch()` equivalent and will use MongoDB for geospatial queries and see how far I get.

**Comment by giorgiofran** [comment] 2020-10-05 10:29
#171

**Comment by MadSheogorath** [comment] 2020-10-10 01:44
I'm eager to use this feature as well. I have two different systems using the same DB. One for making changes in algorithms settings and another for processing those algorithms. It would be extremely handy to be able to reload algorithms settings once they changed without some extra flag checks in DB or (even worse) providing additional external api. Going to reload it manually for now :(

**Comment by giorgiofran** [comment] 2021-01-13 17:16
A new development release have been published. It contains many improvements, among others, watch(), bulkWrite() (partial...) and Decimal 128. If you can, please, give it a try and report bugs and suggestions.

**Comment by giorgiofran** [comment] 2021-04-01 16:27
Also a null-safety pre-release has been published. I close this issue. Feel free to open a new one if needed.

**Closed by giorgiofran** 2021-04-01 16:27 UTC
Labels: enhancement
