### ISSUE TITLE
Microsoft Azure CosmosDB return 'Expected type binData but found string'

### ISSUE THREAD

**Issue by ElvysAraujo** [mongo-dart/mongo_dart#268] opened 2022-01-28 20:28 UTC
Hi! First of all, thanks for this package

I'm having a problem when I try to connect with Microsoft Azure CosmosDB, the `open()` method returns the following error: `MongoDart Error: Expected type binData but found string.`

When I try to connect locally everything works correctly.

Code:
```
import 'dart:developer';
import 'package:mongo_dart/mongo_dart.dart';

const _user = '_user_';
const _password = '_password_';

const _connectionString =
    'mongodb://$_user:$_password@cosmos-saturno-dev.mongo.cosmos.azure.com:10255/?ssl=true&replicaSet=globaldb&retrywrites=false&maxIdleTimeMS=120000&appName=@$_user_@';

class MongoDatabase {
  var db = Db(_connectionString);

  Future<Object?> teste() async {
    try {
      await db.open();
      return await db.listDatabases();
    } catch (e, stacktrace) {
      log(e.toString());
      log(stacktrace.toString());
    }
  }
}
```

Is there any more information I can provide that might help?

(Sorry for my bad english, it's not my native language.)

**Comment by giorgiofran** [comment] 2022-01-30 10:55
O seu inglês é bom ;-) 
I never tested this driver with cosmosDb.
What I suspect is that there can be some incompatibility with MongoDb commands.
For example, while opening, a serverstatus command is poerformed, but I have seen in the cosmosDB documentation that this command is not supported.
Eventually, try to post the stack trace, but I'm not so confident that we can solve this problem unless we change heavily the driver itself.

**Comment by ElvysAraujo** [comment] 2022-01-30 20:43
Thanks for replying.

The `error` and `stacktrace` of the code above return:

![Screen Shot 2022-01-30 at 16 28 06](https://user-images.githubusercontent.com/19196920/151716499-7098c41e-4bf5-4b06-8509-7359fe1573ee.png)

To try and promote more details, I downloaded the lib and used it locally.

As far as I was able to follow, the `open` method at one point calls the `execute` method twice, the first time it returns the following:

![Screen Shot 2022-01-30 at 16 12 25](https://user-images.githubusercontent.com/19196920/151716491-bdc4e711-011f-4b2c-883e-c38f4b6e4ed1.png)

And the second time:

![Screen Shot 2022-01-30 at 16 13 41](https://user-images.githubusercontent.com/19196920/151716496-2bd1686d-ebcf-470f-b6a5-5ea610cf7882.png)

I also tried to identify something in the `executeModernMessage` method, but without success.


I also suspect it's a CosmosDB specificity and I have some alternatives in case you really can't use the `mongo_dart` package.

**Comment by giorgiofran** [comment] 2022-02-01 07:07
Please try with the connection string option `"&authMechanism='SCRAM-SHA-1'"`.
It seems that the problem is in the authentication mechanism. Maybe the cosmosDb does not manage the scramSha256 one.
Or, eventually, try with an older version of the driver (like 0.7.1) that didn't have the scramSha256 protocol.

**Comment by ElvysAraujo** [comment] 2022-02-04 19:44
I'm sorry for answering so late.

Both suggestions did not work, the following errors are returned:

When I tried with an older version of the package:
`{ok: 0.0, errmsg: Command find not supported prior to authentication., code: 115, codeName: CommandNotSupported}`

When I tried with `"&authMechanism='SCRAM-SHA-1'"`:
`MongoDart Error: Provided authentication scheme is not supported : 'SCRAM-SHA-1'`

I also tried with `"&authMechanism='SCRAM-SHA-256'"`:
`MongoDart Error: Provided authentication scheme is not supported : 'SCRAM-SHA-256'`

**Comment by giorgiofran** [comment] 2022-02-10 06:49
Sorry, I gave you the wrong hint:
The authMechanism should not be quoted:
`&authMechanism=SCRAM-SHA-256`
`&authMechanism=SCRAM-SHA-1`
Eventually try also:
`&authMechanism=MONGODB-CR`

**Comment by giorgiofran** [comment] 2022-02-25 13:54
could you solve the problem?

**Comment by giorgiofran** [comment] 2022-10-11 12:15
Hope you solved the problem, I close this issue.

**Closed by giorgiofran** 2022-10-11 12:15 UTC

**Comment by kmcgill88** [comment] 2023-01-03 22:29
I'm seeing this same issue. I tried all three `authMechanism`. Any other ideas @giorgiofran?

**Comment by giorgiofran** [comment] 2023-01-04 03:46
Hi, which version of mongo_dart are you using?

**Comment by kmcgill88** [comment] 2023-01-04 14:09
Sorry I should have let with that. `mongo_dart: ^0.7.4+1` I see `0.8.2` is out too. I'll try that and report back.

**Comment by kmcgill88** [comment] 2023-01-04 22:06
Upgraded to 
```
  mongo_dart 0.8.2
  mongo_dart_query 3.0.0
```

Still saw the issue with these
```
&authMechanism=SCRAM-SHA-256
&authMechanism=SCRAM-SHA-1
```

This one works to connect!
`&authMechanism=MONGODB-CR`

**Comment by giorgiofran** [comment] 2023-01-05 09:41
Great! Thanks for your feedback.
